apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: croptrace-api
spec:
  rules:
    - host: croptrace.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: croptrace-api-prod
                port:
                  number: 80
