apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: croptrace-api-secret
spec:
  refreshInterval: 1h
  data:
    - secretKey: DB_USER
      remoteRef:
        key: croptrace/dev/api
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: croptrace/dev/api
        property: DB_PASSWORD
    - secretKey: MONOLITH_API_KEY
      remoteRef:
        key: croptrace/dev/api
        property: MONOLITH_API_KEY
